FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential nginx
COPY . /FrieghtRates
WORKDIR /FrieghtRates
RUN pip3 install -r Docker/requirements.txt
ENTRYPOINT ["gunicorn", "-w", "4", "-b", "0.0.0.0:9000"]
CMD ["api.index:app"]