version: "3"
services:
    gunicorn:
      build:
        context: ../
        dockerfile: Docker/Dockerfile-web
      ports:
        - "9000:9000"
      volumes:
        - .:/code
      environment:
        - PYTHONUNBUFFERED=0
      depends_on:
        - db
    db:
      build:
        context: .
        dockerfile: Dockerfile-db
      ports:
        - "5432:5432"
    proxy:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      depends_on :
        - gunicorn
      ports:
        - "5000:5000"
