FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
COPY . /web
WORKDIR /
RUN pip3 install -r web/requirements.txt
ENTRYPOINT ["python3"]
CMD ["web/api/index.py"]